<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * AnesthetistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnesthetistRepository extends EntityRepository
{
    /**
     * GET results by param
     * @param array $params
     * @return array
     */
    public function getElements(array $params = [])
    {
        $q = $this->createQueryBuilder('an');
        $this->addFilterByParams($q, $params);

        return $q->getQuery()->getResult();
    }

    /**
     * @param QueryBuilder $q
     * @param array $params
     */
    private function addFilterByParams(QueryBuilder $q, array $params)
    {
        // GET result by id
        if (array_key_exists('by_id', $params)) {
            $q
                ->andWhere($q->expr()->eq('an.id', ':id'))
                ->setParameter('id', $params['by_id']);
        }

        // GET results by keywords
        if (array_key_exists('by_keywords', $params)) {
            $q
                ->andWhere($q->expr()->like('an.name', ':by_keywords'))
                ->setParameter('by_keywords', $params['by_keywords']);
        }
    }
}
