anesthetist_index:
    path:     /
    defaults: { _controller: "AppBundle:Anesthetist:index" }
    methods:  GET

anesthetist_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Anesthetist:show" }
    methods:  GET

anesthetist_new:
    path:     /new
    defaults: { _controller: "AppBundle:Anesthetist:new" }
    methods:  [GET, POST]

anesthetist_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Anesthetist:edit" }
    methods:  [GET, POST]

anesthetist_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Anesthetist:delete" }
    methods:  DELETE
