app_specialist:
    resource: "@AppBundle/Resources/config/routing/specialist.yml"
    prefix:   /specialist

app_anesthetist:
    resource: "@AppBundle/Resources/config/routing/anesthetist.yml"
    prefix:   /anesthetist

app_patient:
    resource: "@AppBundle/Resources/config/routing/patient.yml"
    prefix:   /patient

app_operatingroom:
    resource: "@AppBundle/Resources/config/routing/operatingroom.yml"
    prefix:   /operatingroom

app_session:
    resource: "@AppBundle/Resources/config/routing/session.yml"
    prefix:   /session
