AppBundle\Entity\Anesthetist:
    type: entity
    table: anesthetists
    repositoryClass: AppBundle\Repository\AnesthetistRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToMany:
        sessions:
            targetEntity: AppBundle\Entity\Session
            mappedBy: anesthetists
    lifecycleCallbacks: {  }
