AppBundle\Entity\Doctor:
    type: entity
    table: doctors
    repositoryClass: AppBundle\Repository\DoctorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            column: Name
        type:
            type: string
            length: 255
    ooneToOne:
        Session:
            targetEntity: AppBundle\Entity\Session
            joinColumn:
                name: session_id
                referencedColumnName: id
            cascade: [persist, merge]
            inversedBy: specialist
    manyToMany:
        sessions:
            targetEntity: AppBundle\Entity\Session
            mappedBy: anesthetists
    lifecycleCallbacks: {  }
