AppBundle\Entity\Session:
    type: entity
    table: sessions
    repositoryClass: AppBundle\Repository\SessionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sessionName:
            type: string
            length: 255
            column: session_name
        sessionStart:
            type: datetime
            column: session_start
        sessionEnd:
            type: datetime
            column: session_end
        isSuccess:
            type: boolean
            nullable: true
            column: is_success
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        patientId:
            type: integer
            column: patient_id
    manyToOne:
        patient:
            targetEntity: AppBundle\Entity\Patient
            joinColumn:
                name: patient_id
                referencedColumnName: id
    oneToOne:
        specialist:
            targetEntity: AppBundle\Entity\Specialist
            joinColumn:
                name: specialist_id
                referencedColumnName: id
            cascade: [persist, merge]
            inversedBy: session
    manyToMany:
        anesthetists:
            targetEntity: AppBundle\Entity\Anesthetist
            inversedBy: Session
            joinTable:
                name: session_anesthetists
                joinColumns:
                    session_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    anesthetist_id:
                        referencedColumnName: id
        operatingRooms:
            targetEntity: AppBundle\Entity\OperatingRoom
            inversedBy: Session
            joinTable:
                name: session_operating_rooms
                joinColumns:
                    session_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    operating_room_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
